file(GLOB_RECURSE SOURCES CONFIGURE_DEPENDS "${CMAKE_CURRENT_SOURCE_DIR}/src/*.cpp")
if(SOURCES)
    add_library(cppcoldbv2_common STATIC ${SOURCES})
    target_include_directories(cppcoldbv2_common PUBLIC "${CMAKE_CURRENT_SOURCE_DIR}/include")
    target_compile_features(cppcoldbv2_common PUBLIC cxx_std_20)
else()
    add_library(cppcoldbv2_common INTERFACE)
    target_include_directories(cppcoldbv2_common INTERFACE "${CMAKE_CURRENT_SOURCE_DIR}/include")
    target_compile_features(cppcoldbv2_common INTERFACE cxx_std_20)
endif()
