file(GLOB_RECURSE SOURCES CONFIGURE_DEPENDS "${CMAKE_CURRENT_SOURCE_DIR}/src/*.cpp")
if(SOURCES)
    add_library(cppcoldbv2 STATIC ${SOURCES})
else()
    add_library(cppcoldbv2 INTERFACE)
endif()

if(SOURCES)
    target_include_directories(cppcoldbv2 PUBLIC "${CMAKE_CURRENT_SOURCE_DIR}/include")
    target_compile_features(cppcoldbv2 PUBLIC cxx_std_20)
    target_link_libraries(cppcoldbv2 PUBLIC cppcoldbv2_common cppcoldbv2_engine cppcoldbv2_infrastructure cppcoldbv2_sql)
else()
    target_include_directories(cppcoldbv2 INTERFACE "${CMAKE_CURRENT_SOURCE_DIR}/include")
    target_link_libraries(cppcoldbv2 INTERFACE cppcoldbv2_common cppcoldbv2_engine cppcoldbv2_infrastructure cppcoldbv2_sql)
endif()
