file(GLOB_RECURSE SOURCES CONFIGURE_DEPENDS "${CMAKE_CURRENT_SOURCE_DIR}/src/*.cpp")
if(SOURCES)
    add_library(cppcoldbv2_sql STATIC ${SOURCES})
else()
    add_library(cppcoldbv2_sql INTERFACE)
endif()

if(SOURCES)
    target_include_directories(cppcoldbv2_sql PUBLIC "${CMAKE_CURRENT_SOURCE_DIR}/include")
    target_compile_features(cppcoldbv2_sql PUBLIC cxx_std_20)
    target_link_libraries(cppcoldbv2_sql PUBLIC cppcoldbv2_common cppcoldbv2_engine)
else()
    target_include_directories(cppcoldbv2_sql INTERFACE "${CMAKE_CURRENT_SOURCE_DIR}/include")
    target_link_libraries(cppcoldbv2_sql INTERFACE cppcoldbv2_common cppcoldbv2_engine)
endif()
