file(GLOB_RECURSE SOURCES CONFIGURE_DEPENDS "${CMAKE_CURRENT_SOURCE_DIR}/src/*.cpp")
if(SOURCES)
    add_library(cppcoldbv2_engine STATIC ${SOURCES})
else()
    add_library(cppcoldbv2_engine INTERFACE)
endif()

if(SOURCES)
    target_include_directories(cppcoldbv2_engine PUBLIC "${CMAKE_CURRENT_SOURCE_DIR}/include")
    target_compile_features(cppcoldbv2_engine PUBLIC cxx_std_20)
    target_link_libraries(cppcoldbv2_engine PUBLIC cppcoldbv2_common)
else()
    target_include_directories(cppcoldbv2_engine INTERFACE "${CMAKE_CURRENT_SOURCE_DIR}/include")
    target_link_libraries(cppcoldbv2_engine INTERFACE cppcoldbv2_common)
endif()
